//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachments
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public int Source { get; set; }
        public Nullable<int> RelatedId { get; set; }
        public int Readperm { get; set; }
        public string Filename { get; set; }
        public string Shortfilename { get; set; }
        public string Description { get; set; }
        public string Filetype { get; set; }
        public long Filesize { get; set; }
        public string Originalfilename { get; set; }
        public int Downloads { get; set; }
        public string Party { get; set; }
        public Nullable<System.DateTime> ExpiredTime { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual Projects Projects { get; set; }
    }
}
