//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cashflows
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int Sequence { get; set; }
        public System.DateTime Date { get; set; }
        public int Year { get; set; }
        public int Quater { get; set; }
        public int Month { get; set; }
        public double EnergyYield { get; set; }
        public double Revenue { get; set; }
        public double OPEX { get; set; }
        public double PropertyTax { get; set; }
        public double BusinessTax { get; set; }
        public double LoanTenorDurableLife { get; set; }
        public double REITFCF { get; set; }
        public double REITDividend { get; set; }
        public double PrincipalBalance { get; set; }
        public double Principal { get; set; }
        public double Interest { get; set; }
        public double DSRA { get; set; }
        public double ReservePayback { get; set; }
        public double RemovalCost { get; set; }
        public double FCFBeforeLoanRepayment { get; set; }
        public double Repayment { get; set; }
        public double DSCR { get; set; }
        public double DSCRPosterior { get; set; }
        public double AMFee { get; set; }
        public double FCF { get; set; }
        public double Dividend { get; set; }
        public double CashBalance { get; set; }
        public double CumulativeDividend { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public byte[] Timestamp { get; set; }
        public double FixAssetInvestment { get; set; }
        public double FixAssetBookValue { get; set; }
    
        public virtual Projects Projects { get; set; }
    }
}
