//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnergyYields
    {
        public string Id { get; set; }
        public int ProjectId { get; set; }
        public long YearMonthDayHour { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Day { get; set; }
        public int Hour { get; set; }
        public double Temperature { get; set; }
        public double SunRadiation { get; set; }
        public double ACElectricity { get; set; }
        public double DCElectricity { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<int> PCS { get; set; }
        public Nullable<double> CO2 { get; set; }
        public Nullable<int> Minutes { get; set; }
        public Nullable<double> IntensityRadiation { get; set; }
        public Nullable<double> ACPower { get; set; }
        public Nullable<double> DCPower { get; set; }
        public Nullable<double> PowerSelling { get; set; }
        public Nullable<double> PowerPurchase { get; set; }
        public Nullable<double> ACVoltage { get; set; }
        public Nullable<double> DCVoltage { get; set; }
        public Nullable<double> ACCurrent { get; set; }
        public Nullable<double> DCCurrent { get; set; }
    }
}
