//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterApplications
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public string ApplyCompany { get; set; }
        public string ApplyDepartment { get; set; }
        public string ApplyerName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public System.DateTime WorkDate { get; set; }
        public string WorkContent { get; set; }
        public string Responser { get; set; }
        public string SafeManager { get; set; }
        public string AttentionMatter { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual Projects Projects { get; set; }
    }
}
