//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtenalWeatherDatas
    {
        public int Id { get; set; }
        public double GeoLongitude { get; set; }
        public double GeoLatitude { get; set; }
        public string GeoCountryCode { get; set; }
        public string GeoAreaName { get; set; }
        public string GeoAreaApiId { get; set; }
        public string GeoRelatedStation { get; set; }
        public System.DateTime TimeSunRise { get; set; }
        public System.DateTime TimeSunSet { get; set; }
        public System.DateTime TimeApiUpdate { get; set; }
        public string WeatherName { get; set; }
        public string WeatherDescription { get; set; }
        public string WeatherApiId { get; set; }
        public string WeatherApiIcon { get; set; }
        public string DisasterName { get; set; }
        public string DisasterLevel { get; set; }
        public double TemperatureCelsius { get; set; }
        public Nullable<double> TemperatureAreaMaxCelsius { get; set; }
        public Nullable<double> TemperatureAreaMinCelsius { get; set; }
        public string TemperatureUnit { get; set; }
        public double AtmosphericPressurehPa { get; set; }
        public Nullable<double> AtmosphericPressureSeaBasehPa { get; set; }
        public Nullable<double> AtmosphericPressureGroundBasehPa { get; set; }
        public double HumidityPercent { get; set; }
        public Nullable<double> CloudinessPercent { get; set; }
        public Nullable<double> VisibilityMeter { get; set; }
        public double WindSpeedMeterPerSecond { get; set; }
        public double WindDirectionDegrees { get; set; }
        public string WindDirectionCode { get; set; }
        public Nullable<double> PrecipitationVolumnMM { get; set; }
        public string PrecipitationMode { get; set; }
        public Nullable<double> VolumnRainThreeHour { get; set; }
        public Nullable<double> VolumnSnowThreeHour { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<int> ProjectId { get; set; }
    }
}
