//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Functions2
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public int FunctionType { get; set; }
        public bool OperateLogEnabled { get; set; }
        public bool DataLogEnabled { get; set; }
        public bool IsLocked { get; set; }
        public string Url { get; set; }
        public bool IsController { get; set; }
        public bool IsAjax { get; set; }
        public bool IsChild { get; set; }
        public bool IsCustom { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
