//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funds
    {
        public Funds()
        {
            this.AssetPositions = new HashSet<AssetPositions>();
            this.FundInvestors = new HashSet<FundInvestors>();
            this.FundTrades = new HashSet<FundTrades>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime FoundDate { get; set; }
        public string UserId { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public byte[] Timestamp { get; set; }
        public string Code { get; set; }
        public string Exchange { get; set; }
        public double IssuedVolumn { get; set; }
        public string Yield { get; set; }
        public string InvestCompany { get; set; }
        public string AssetOperationCompany { get; set; }
        public string OperationCompany { get; set; }
        public string AssetType { get; set; }
        public decimal ManagementFeeRate { get; set; }
        public string SPCMonth { get; set; }
        public string Lender { get; set; }
        public decimal SoldPrice { get; set; }
        public decimal SoldVolumn { get; set; }
        public string EquipmentOwner { get; set; }
        public string Electricitier { get; set; }
        public string IPPManageContract { get; set; }
    
        public virtual ICollection<AssetPositions> AssetPositions { get; set; }
        public virtual ICollection<FundInvestors> FundInvestors { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<FundTrades> FundTrades { get; set; }
    }
}
