//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentReports
    {
        public IncidentReports()
        {
            this.Projects = new HashSet<Projects>();
        }
    
        public string Id { get; set; }
        public string Indication { get; set; }
        public string EstimateFinishDate { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<System.DateTime> HappenedDate { get; set; }
        public string Description { get; set; }
        public string Progress { get; set; }
        public Nullable<int> FirstCategory { get; set; }
        public Nullable<int> SecondCategory { get; set; }
        public Nullable<int> AffectRange { get; set; }
        public Nullable<int> DealType { get; set; }
        public Nullable<int> Degree { get; set; }
        public Nullable<int> Dealer { get; set; }
        public string Cost { get; set; }
        public Nullable<int> Status { get; set; }
        public int IncidentNum { get; set; }
    
        public virtual ICollection<Projects> Projects { get; set; }
    }
}
