//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperateLogs
    {
        public OperateLogs()
        {
            this.DataLogs = new HashSet<DataLogs>();
        }
    
        public int Id { get; set; }
        public string FunctionKey { get; set; }
        public string FunctionName { get; set; }
        public string Operator_UserID { get; set; }
        public string Operator_Name { get; set; }
        public string Operator_NickName { get; set; }
        public string Operator_Ip { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual ICollection<DataLogs> DataLogs { get; set; }
    }
}
