//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectProfiles
    {
        public int Id { get; set; }
        public string Location { get; set; }
        public string PVManufacturer { get; set; }
        public string PCSManufacturer { get; set; }
        public double PCSCapacity { get; set; }
        public string Developer { get; set; }
        public string IndependentPowerProducer { get; set; }
        public string Landlord { get; set; }
        public string AffiliatedMunicipality { get; set; }
        public string EPC { get; set; }
        public string Lender { get; set; }
        public string TKInvestor { get; set; }
        public string ElectricityPurchaser { get; set; }
        public double InitialInvestmentRatio { get; set; }
        public Nullable<double> IRR { get; set; }
        public double YearlyEnergyYieldEstimation { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<double> NonLeverIRR { get; set; }
        public double TAMonthlyEnergyYieldEstimation { get; set; }
        public double TADailySunRadiationEstimation { get; set; }
    
        public virtual Projects Projects { get; set; }
    }
}
