//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyItems
    {
        public PropertyItems()
        {
            this.InitialCostInfoes = new HashSet<InitialCostInfoes>();
            this.ProjectProperties = new HashSet<ProjectProperties>();
            this.ProjectPropertyPaymentDetails = new HashSet<ProjectPropertyPaymentDetails>();
            this.PropertyItemExtensions = new HashSet<PropertyItemExtensions>();
            this.PropertyItems1 = new HashSet<PropertyItems>();
            this.PropertyPayments = new HashSet<PropertyPayments>();
            this.ScenarioInputs = new HashSet<ScenarioInputs>();
        }
    
        public int Id { get; set; }
        public string Key { get; set; }
        public string Label { get; set; }
        public string Unit { get; set; }
        public int DataType { get; set; }
        public int CatalogId { get; set; }
        public int Sequence { get; set; }
        public string Options { get; set; }
        public string Formula { get; set; }
        public string DefaultValue { get; set; }
        public int Type { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Tips { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual ICollection<InitialCostInfoes> InitialCostInfoes { get; set; }
        public virtual ICollection<ProjectProperties> ProjectProperties { get; set; }
        public virtual ICollection<ProjectPropertyPaymentDetails> ProjectPropertyPaymentDetails { get; set; }
        public virtual PropertyCatalogs PropertyCatalogs { get; set; }
        public virtual ICollection<PropertyItemExtensions> PropertyItemExtensions { get; set; }
        public virtual ICollection<PropertyItems> PropertyItems1 { get; set; }
        public virtual PropertyItems PropertyItems2 { get; set; }
        public virtual ICollection<PropertyPayments> PropertyPayments { get; set; }
        public virtual ICollection<ScenarioInputs> ScenarioInputs { get; set; }
    }
}
