//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrSells
    {
        public int Id { get; set; }
        public int PowerTradeId { get; set; }
        public string StationName { get; set; }
        public double Power { get; set; }
        public double MoneyWithoutTax { get; set; }
        public double MoneyForPower { get; set; }
        public double TaxForPower { get; set; }
        public Nullable<System.DateTime> MoneyInDate { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual PowerTrades PowerTrades { get; set; }
    }
}
