//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedules
    {
        public Schedules()
        {
            this.ScheduleComments = new HashSet<ScheduleComments>();
            this.ScheduleDependences = new HashSet<ScheduleDependences>();
            this.ScheduleDependences1 = new HashSet<ScheduleDependences>();
            this.Schedules1 = new HashSet<Schedules>();
        }
    
        public int Id { get; set; }
        public int CatalogId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Priority { get; set; }
        public string CssClass { get; set; }
        public System.DateTime Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public int Status { get; set; }
        public string ReportUserId { get; set; }
        public string OwnerId { get; set; }
        public int ProjectId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int ProcessPercentage { get; set; }
        public bool IsDetail { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        public virtual Projects Projects { get; set; }
        public virtual ScheduleCatalogs ScheduleCatalogs { get; set; }
        public virtual ICollection<ScheduleComments> ScheduleComments { get; set; }
        public virtual ICollection<ScheduleDependences> ScheduleDependences { get; set; }
        public virtual ICollection<ScheduleDependences> ScheduleDependences1 { get; set; }
        public virtual ICollection<Schedules> Schedules1 { get; set; }
        public virtual Schedules Schedules2 { get; set; }
        public virtual Users Users { get; set; }
    }
}
