//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Comments = new HashSet<Comments>();
            this.Funds = new HashSet<Funds>();
            this.InnerMessages = new HashSet<InnerMessages>();
            this.InnerMessages1 = new HashSet<InnerMessages>();
            this.Projects = new HashSet<Projects>();
            this.Scenarios = new HashSet<Scenarios>();
            this.ScheduleComments = new HashSet<ScheduleComments>();
            this.Schedules = new HashSet<Schedules>();
            this.SubscibeProjects = new HashSet<SubscibeProjects>();
            this.UserActivities = new HashSet<UserActivities>();
            this.UserClaims = new HashSet<UserClaims>();
            this.UserLogins = new HashSet<UserLogins>();
            this.WeeklyTasks = new HashSet<WeeklyTasks>();
            this.Organizations = new HashSet<Organizations>();
            this.Roles = new HashSet<Roles>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string NickName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public byte[] Timestamp { get; set; }
        public string Discriminator { get; set; }
    
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual ICollection<Funds> Funds { get; set; }
        public virtual ICollection<InnerMessages> InnerMessages { get; set; }
        public virtual ICollection<InnerMessages> InnerMessages1 { get; set; }
        public virtual ICollection<Projects> Projects { get; set; }
        public virtual ICollection<Scenarios> Scenarios { get; set; }
        public virtual ICollection<ScheduleComments> ScheduleComments { get; set; }
        public virtual ICollection<Schedules> Schedules { get; set; }
        public virtual ICollection<SubscibeProjects> SubscibeProjects { get; set; }
        public virtual ICollection<UserActivities> UserActivities { get; set; }
        public virtual ICollection<UserClaims> UserClaims { get; set; }
        public virtual ICollection<UserLogins> UserLogins { get; set; }
        public virtual ICollection<WeeklyTasks> WeeklyTasks { get; set; }
        public virtual ICollection<Organizations> Organizations { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
